### ISSUE TITLE
mpv-build on wheezy

### ISSUE THREAD

**Issue by mrkapqa** [nyxi/buildscripts-debian#1]
hello emil,

i would like to thank you for your webpage that helped me a great deal on installing mpv on wheezy and even on squeeze.

unfortunately i can't find the "script" no longer as your webpage seems down.l

would you mind sharing it once again so that i can save for further use?

thank you very much,

richard

**Comment by nyxi** [comment]
Hi,

I recently cleaned out my old website, I assume you are referring to the post with instructions on how to compile mpv on Debian. I updated that post a bit and reposted it [here](https://nyxi.eu/compiling-mpv-on-debian.html#compiling-mpv-on-debian).

**Comment by mrkapqa** [comment]
Hello ,

yes, that were the instructions.
i need mpv to use with youtube-viewer by trizen. to make the mpv  
effective i had to install first libfribidi-dev and libgnutls-dev  
(libgnutls28-dev on jessie) and then pass "echo --enable-gnutls >>  
ffmpeg_options" before the command rebuild.
lately it failed to build on wheezy because it was asking for harfbuzz  
or fontconfig , so a developer of mpv helped out - had to adjust  
libass , so that it worked.

i am going to try this out now on a T61 Lenovo - hope it is still valid.

Thank you very much,

Richard


Zitat von nyxi <notifications@github.com>:

**Comment by mrkapqa** [comment]
Yes, building on Wheezy is no more active with your instructions that  
you posted "mpv on wheezy in 2014"

i have to use this instruction here

sudo aptitude install autoconf  automake  libasound2-dev  
libegl1-mesa-dev  libfontconfig-dev  libfreetype6-dev  libfribidi-dev  
libgl1-mesa-dev libgnutls-dev libtool libx11-dev libxext-dev  
libxinerama-dev libxrandr-dev  libxv-dev  pkg-config python   
x11proto-core-dev yasm
./update
./clean
cd libass
git checkout 9a2b38e8f5957418362e86b525f72794565deedd
cd ..
./build -j2


Zitat von nyxi <notifications@github.com>:

**Comment by nyxi** [comment]
Updated the instructions again after testing them out on a clean Debian 8.4 VM.

**Comment by mrkapqa** [comment]
hello emil,

could you please pass me the instructions that you posted previously  
on your webpage for compiling mpv on wheezy in 2014? that where those  
that worked best for me on squeeze and wheezy.

thanks

richie

Zitat von nyxi <notifications@github.com>:
